### ISSUE TITLE
Understanding the ascii braille mapping

### ISSUE THREAD

**Issue by Benedict-Carling** [PaigeBraille/paige-website#14]
@Gos2two Is there meaning in the order of the items within this function?

https://github.com/PaigeBraille/paige-website/blob/853652a38e6587a50b50ea27ee31269367cd8dc9/pages/translate.tsx#L59-L72

If not potentially we don't need to redefine the array we can use the keys from this object

https://github.com/PaigeBraille/paige-website/blob/853652a38e6587a50b50ea27ee31269367cd8dc9/components/BrailleMapping.tsx#L1-L69

Using `const asciiBrailleKeys = Object.keys(asciiBraille);`

However it is worth noting that the array has one extra character "\n" which is not present in the dictionary, potentially we could add the object `"\n" : { "braille" : "\n "}` to asciiBraiile object first

**Comment by Gos2two** [comment]
The order from the first object actually matters, but it is a great idea to make everything more modular! I can spend some time re-writing the map this week! New line can go last so it does not affect it.

**Comment by Gos2two** [comment]
Sorted by @Benedict-Carling
